import slider from './slider/slider'
import loader from './loader/loader'
import listTrigger from './list-trigger/list-trigger'
import footer from './app-footer/app-footer'
import header from './header/header'
import button from './button/button'
import icon from './icon/icon'
import dynamicBackground from './dynamic-background/dynamic-background'
